CoreDemo/Areas/Admin/Controllers/WriterController.cs
using CoreDemo.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AllowAnonymous]
    public class WriterController : Controller
    {
        public IActionResult Index()
        {

            return View();
        }

        public IActionResult WriterList()
        {
            var jsonWriters = JsonConvert.SerializeObject(writers);
            return Json(jsonWriters);
        }

        public IActionResult GetWriterByID(int id)
        {
            var findwriter = writers.FirstOrDefault(x => x.Id == id);
            var jsonWriters = JsonConvert.SerializeObject(findwriter);
            return Json(jsonWriters);
        }

        [HttpPost]
        public IActionResult AddWriter(WriterClass w)
        {
            writers.Add(w);
            var jsonWriters = JsonConvert.SerializeObject(w);
            return Json(jsonWriters);
        }

        public IActionResult DeleteWriter(int id)
        {
            var writer = writers.FirstOrDefault(x => x.Id == id);
            writers.Remove(writer);
            return Json(writer);
        }

        public IActionResult UpdateWriter(WriterClass w)
        {
            var writer = writers.FirstOrDefault(x => x.Id == w.Id);
            writer.Name = w.Name;
            var jsonWriter = JsonConvert.SerializeObject(w);
            return Json(jsonWriter);
        }

        public static List<WriterClass> writers = new List<WriterClass>
        {
            new WriterClass
            {
                Id=1,
                Name="Ayşe"
            },

            new WriterClass
            {
                Id=2,
                Name="Ahmet"
            },
            new WriterClass
            {
                Id=3,
                Name="Buse"
            }
        };
    }
}

CoreDemo/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using CoreDemo.Models;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{
    public class WriterController : Controller
    {

        WriterManager wm = new WriterManager(new EfWriterRepository());
        [Authorize]
        public IActionResult Index()
        {
            var usermail = User.Identity.Name;
            ViewBag.v = usermail;
            Context c = new Context();
            var writerName =c.Writers.Where(x=>x.WriterMail==usermail).Select(y=>y.WriterName).FirstOrDefault();
            ViewBag.v2 = writerName;
            return View();
        }
        public IActionResult WriterProfile()
        {
            return View();
        }
      
        public IActionResult WriterMail()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult Test()
        {
            return View();
        }
        [AllowAnonymous]

        public PartialViewResult WriterNavbarPartial()
        {
            return PartialView();
        }
        [AllowAnonymous]

        public PartialViewResult WriterFooterPartial()
        {
            return PartialView();
        }

        [HttpGet]
        public IActionResult WriterEditProfile()
        {
            Context c = new Context();
            var usermail = User.Identity.Name;
            var writerID = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterID).FirstOrDefault();

            var writervalues = wm.TGetById(writerID);
            return View(writervalues);
        }

        [HttpPost]
        public IActionResult WriterEditProfile(Writer p)
        {
            WriterValidator wl = new WriterValidator();
            ValidationResult result=wl.Validate(p);
            if (result.IsValid)
            {
                wm.TUpdate(p);
                return RedirectToAction("Index", "Dashboard");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult WriterAdd()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult WriterAdd(AddProfileImage p) 
        {
            Writer w = new Writer();
            if (p.WriterImage!=null)
            {
                var extension = Path.GetExtension(p.WriterImage.FileName);
                var newimagename = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/WriterImageFiles/", newimagename);
                var stream = new FileStream(location, FileMode.Create);
                p.WriterImage.CopyTo(stream);
                w.WriterImage = newimagename;
            }
            w.WriterMail = p.WriterMail;
            w.WriterName = p.WriterName;
            w.WriterPassword = p.WriterPassword;
            w.WriterStatus = p.WriterStatus;
            w.WriterAbout = p.WriterAbout;

            wm.TAdd(w);
            return RedirectToAction("Index", "Dashboard");
        }


    }
}

CoreDemo/Views/Writer/Index.cshtml
@{
    Layout = null;
}

<h1>Burası yazar paneli</h1>
<br />
<br />

<h2>@ViewBag.v</h2>
<br />
<h3>@ViewBag.v2</h3>

CoreDemo/Views/Writer/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<h1>TEST</h1>

CoreDemo/Views/Writer/WriterAdd.cshtml
@model CoreDemo.Models.AddProfileImage
@{
    ViewData["Title"] = "WriterAdd";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<form class="form-group" method="post" enctype="multipart/form-data">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Yazar Profil Bilgileri Düzenleme</h4>
                @Html.HiddenFor(x => x.WriterID, new { @class = "form-control" })
                <div class="forms-sample">
                    <div class="form-group">
                        <label for="exampleInputName1">Yazar Ad Soyad</label>
                        @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Mail Adresi</label>
                        @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword4">Şifre</label>
                        @Html.PasswordFor(x => x.WriterPassword, new { @class = "form-control" })

                    </div>

                    <div class="form-group">
                        <label>Yazar Görsel</label>
                        <input type="file" name="WriterImage"/>
                    </div>

                    <div class="form-group">
                        <label for="exampleTextarea1">Yazar Hakkında</label>
                        @Html.TextAreaFor(x => x.WriterAbout, 10, 3, new { @class = "form-control" })

                    </div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">Kaydet</button>
                    <button class="btn btn-light">İptal</button>
                </div>
            </div>
        </div>
    </div>
</form>

CoreDemo/Views/Writer/WriterEditProfile.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewData["Title"] = "WriterEditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>WriterEditProfile</h1>
@using (Html.BeginForm("WriterEditProfile", "Writer", FormMethod.Post)) 
{
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Yazar Profil Bilgileri Düzenleme</h4>
            @Html.HiddenFor(x => x.WriterID, new { @class = "form-control" })
            <form class="forms-sample">
                <div class="form-group">
                    <label for="exampleInputName1">Yazar Ad Soyad</label>
                    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail3">Mail Adresi</label>
                    @Html.TextBoxFor(x => x.WriterMail, new { @class = "form-control" })

                </div>
                <div class="form-group">
                    <label for="exampleInputPassword4">Şifre</label>
                    @Html.PasswordFor(x => x.WriterPassword, new { @class = "form-control" })

                </div>

                <div class="form-group">
                    <label>Yazar Görsel</label>
                    <input type="file" name="img[]" class="file-upload-default">
                    <div class="input-group col-xs-12">
                        <input type="text" class="form-control file-upload-info" disabled placeholder="Upload Image">
                        <span class="input-group-append">
                            <button class="file-upload-browse btn btn-gradient-primary" type="button">Resim Seç</button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="exampleTextarea1">Yazar Hakkında</label>
                    @Html.TextAreaFor(x => x.WriterAbout, 10, 3, new { @class = "form-control" })

                </div>
                <button type="submit" class="btn btn-gradient-primary mr-2">Güncelle</button>
                <button class="btn btn-light">İptal</button>
            </form>
        </div>
    </div>
</div>
}

CoreDemo/Views/Writer/WriterFooterPartial.cshtml
@{
    Layout = null;
}
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">
            Copyright Tüm hakları saklıdır.
            | @DateTime.Now.Year
        </span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">
            Yazar Paneli
            <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">
           Core 5.0 Proje Kampı
            </a>
        </span>
    </div>
</footer>

CoreDemo/Views/Writer/WriterMail.cshtml
@{
    Layout = null;
}

<h1>Yazar Mail Paneli</h1>

CoreDemo/Views/Writer/WriterNavbarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="~/writer/assets/images/faces/face1.jpg" alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">Yazar Adı Soyadı</span>
                    <span class="text-secondary text-small">Yazılım Mühendisi</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Dashboard/Index/">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterEditProfile/">
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogListByWriter/">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogAdd/">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterMessage/">
                <span class="menu-title">Mesajlar</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Notification/AllNotification/">
                <span class="menu-title">Bildirimler</span>
                <i class="mdi mdi-call-merge menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/Index/">
                <span class="menu-title">Siteye Git</span>
                <i class="mdi mdi-car menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterEditProfile/">
                <span class="menu-title">Ayarlar</span>
                <i class="mdi mdi-settings menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Login/WriterLogOut/">
                <span class="menu-title">Çıkış Yap</span>
                <i class="mdi mdi-logout-variant menu-icon"></i>
            </a>
        </li>
    </ul>
</nav>

CoreDemo/Views/Writer/WriterProfile.cshtml
@{
    Layout = null;
}

<h1>Burası yazar profil sayfası</h1>